trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: CodeQLScan
    displayName: 'CodeQL Scan'
    steps:
      - checkout: self

      - script: |
          echo '##[group]Install CodeQL CLI'
          curl -L https://github.com/github/codeql-cli-binaries/releases/latest/download/codeql-linux64.zip -o codeql-linux64.zip
          unzip -qq codeql-linux64.zip
          export PATH=$PATH:$(pwd)/codeql-linux64/bin
          echo '##[endgroup]'

      - script: |
          echo '##[group]Run CodeQL Analysis'
          codeql database create --language=javascript --source-root . --database codeql-db
          codeql database analyze --database codeql-db --format=sarif-latest --output codeql-results.sarif
          echo '##[endgroup]'
        displayName: 'Run CodeQL Analysis'