trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: CodeQLScan
    displayName: 'CodeQL Scan'
    steps:
      - checkout: self

      - script: |
          echo '##[group]Install CodeQL CLI'
          curl -L -o codeql-bundle.zip https://github.com/github/codeql-bundle/releases/latest/download/codeql-bundle.zip
          unzip -qq codeql-bundle.zip
          export PATH=$PATH:$(pwd)/codeql-bundle-*/codeql-cli/bin
          echo '##[endgroup]'

      - script: |
          echo '##[group]Run CodeQL Analysis'
          codeql database create --language=javascript --source-root . --database codeql-db
          codeql query run --database codeql-db --format=sarif-latest --output codeql-results.sarif $(pwd)/codeql-bundle-*/codeql-suites/javascript/ql/src
          echo '##[endgroup]'
        displayName: 'Run CodeQL Analysis'
