# This Azure pipelines uses a PowerShell task to run CodeQL on the agent/runner and send results back to GitHub.

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

jobs: 
  # Install Node
  - job: NodeJS
    displayName: Node JS
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '16.x'
        displayName: 'Install Node.js'

      - script: |
          cd $(System.DefaultWorkingDirectory)
          npm install
        displayName: 'npm install and test'

  # Run CodeQL
  - job: CodeQL_CLI 
    displayName: CodeQL Scan
    dependsOn: NodeJS
    steps:
      - checkout: self

      # Use PowerShell to checkout CodeQL Anywhere repo as a submodule
      - task: PowerShell@2
        displayName: 'Checkout codeql-anywhere'
        inputs:
          targetType: inline
          script: |
            if (Test-Path './.git/modules/codeql-anywhere') {rm -rf './.git/modules/codeql-anywhere'}
            git submodule add https://github.com/david-wiggs/codeql-anywhere.git
          pwsh: true

      # Use PowerShell to run the CodeQL scan and return SARIF results to GitHub
      - task: PowerShell@2
        displayName: 'Run New-CodeQLScan.ps1'
        inputs:
          targetType: filePath
          filePath: 'codeql-anywhere/resources/scripts/New-CodeQLScan.ps1'
          pwsh: true
        env:
          GITHUB_TOKEN: $(GHAS_ADO)
