# This Azure pipelines uses a PowerShell task to run CodeQL on the agent/runner and send results back to GitHub.

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
  # install Node
  - job: NodeJS
    displayName: Node JS
    steps:
      - task: NodeTool@0
        inputs:
          versionSource: 'spec' # 'spec' | 'fromFile'. Required. Source of version. Default: spec.
          versionSpec: '16.x'
        displayName: 'Install Node.js'

      - script: |
          npm install
        displayName: 'npm install and test'

      - script: |
          wget https://github.com/github/codeql-action/releases/download/codeql-bundle-v2.14.0/codeql-runner-linux
          chmod +x codeql-runner-linux
        displayName: 'Get latest CodeQL package. Install on Agent.'

      - script: |
          ./codeql-runner-linux init \
          --repository DevDivOrg/codeql-zero-to-hero/security \
          --github-url https://github.com \
          --github-auth $GHAS_ADO \
          --config-file .github/codeql/codeql-config.yml 
        displayName: 'Initialize CodeQL Executable and create a CodeQL database'
