trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo '##[group]Install CodeQL CLI'
      curl -L https://github.com/github/codeql-cli-binaries/releases/latest/download/codeql.zip --output codeql.zip
      unzip -qq codeql.zip -d codeql
      echo '##[endgroup]'
    displayName: 'Install CodeQL CLI'

  - script: |
      echo '##[group]Analyze CodeQL database'
      ./codeql/codeql database create --language=javascript --source-root . codeql-db
      ./codeql/codeql query run --database codeql-db --output results.sarif
      echo '##[endgroup]'
    displayName: 'Analyze CodeQL'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: CodeQL
      summaryFileLocation: results.sarif
